### ISSUE TITLE
Deleting site issue

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/Plugin-BackgroundProcessing#5]
Hello, can anyone reproduce deleting the site issue while this plugin (BackgroundProcessing) is enabled?
https://github.com/HelloZeroNet/ZeroHello/issues/115#issuecomment-466800449

**Comment by purplesyringa** [comment]
Weird, will check this issue.

**Comment by purplesyringa** [comment]
Actually, I think this was fixed like half a year ago. Could you make sure this is reproducable on the latest version of the plugin please?

**Comment by slrslr** [comment]
you are right. When i download latest plugin files and restarted zeronet, deleting site works, no problem. thank you
